services:
  image-adjuster-backend:
    build:
      context: ./backend
    container_name: image-adjuster-backend
    ports:
      - "8000:8000"
    volumes:
      - image-adjuster-uploads:/app/uploads
      - image-adjuster-outputs:/app/outputs
    networks:
      - image-adjuster-network

  image-adjuster-frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://localhost:8000  # Passed to Vite during build
    container_name: image-adjuster-frontend
    ports:
      - "3000:80"
    depends_on:
      - image-adjuster-backend
    networks:
      - image-adjuster-network

volumes:
  image-adjuster-uploads:
  image-adjuster-outputs:

networks:
  image-adjuster-network:
    driver: bridge
