name: Build, Push, and Deploy Docker Images

on:
  push:
    branches: [master]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build and push backend
        run: |
          docker build -t cyberaka/image-adjuster-backend:latest ./backend
          docker push cyberaka/image-adjuster-backend:latest

      - name: Build and push frontend
        run: |
          docker build --build-arg VITE_BACKEND_URL=https://image.ajitkids.com/api -t cyberaka/image-adjuster-frontend:latest ./frontend
          docker push cyberaka/image-adjuster-frontend:latest

      - name: Deploy to Ubuntu server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull cyberaka/image-adjuster-backend:latest
            docker pull cyberaka/image-adjuster-frontend:latest

            docker stop image-adjuster-backend || true
            docker rm image-adjuster-backend || true

            docker stop image-adjuster-frontend || true
            docker rm image-adjuster-frontend || true

            docker run -d --name image-adjuster-backend -p 8000:8000 -v image-adjuster-uploads:/app/uploads -v image-adjuster-outputs:/app/outputs cyberaka/image-adjuster-backend:latest

            docker run -d --name image-adjuster-frontend -p 3000:80 cyberaka/image-adjuster-frontend:latest
